# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c59b4f0d493008195d2b6314b86c8dfd8474f0d3a101f74351e51e64a98deb46b8632044f78fc3161a4471824227eabfeb93d80233759d9d15f49d33eb800c6a

test:
  secret_key_base: f515e03bb50285cd3d1cb052a726cfc51fcac88ae77519bc6c333f2d3050f0c4bd0721a08a785d0acaa6dd9ce22735a0ddeb6eaacf7046a9c7a1e34a12ac3a22

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
